{% set version = "0.8.8" %}

package:
  name: aws-c-mqtt
  version: {{ version }}

source:
  url: https://github.com/awslabs/aws-c-mqtt/archive/v{{ version }}.tar.gz
  sha256: bbd07535b50b79a4ee1cf07d2713d4046181c676242f1533ec1eab14be07027a
  patches:
    # see https://github.com/awslabs/aws-c-mqtt/issues/257
    - patches/0001-increase-timeouts-for-two-mqtt5_client_tests.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-mqtt", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - ninja
  host:
    - aws-c-common
    - aws-c-io
    - aws-c-http

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-mqtt${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/mqtt/mqtt.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\mqtt\\mqtt.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-mqtt.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-mqtt
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the MQTT 3.1.1 specification.

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
