schema_version: 1

context:
  version: "0.13.3"

package:
  name: aws-c-mqtt
  version: ${{ version }}

source:
  url: https://github.com/awslabs/aws-c-mqtt/archive/v${{ version }}.tar.gz
  sha256: 1dfc11d6b3dc1a6d408df64073e8238739b4c50374078d36d3f2d30491d15527

build:
  number: 1

requirements:
  build:
    - cmake
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ninja
  host:
    - aws-c-common
    - aws-c-io
    - aws-c-http
  run_exports:
    - ${{ pin_subpackage("aws-c-mqtt", upper_bound="x.x.x") }}

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/lib/libaws-c-mqtt${SHLIB_EXT}
          - test -f $PREFIX/include/aws/mqtt/mqtt.h
      - if: win
        then:
          - if not exist %LIBRARY_INC%\\aws\\mqtt\\mqtt.h exit 1
          - if not exist %PREFIX%\\Library\\bin\\aws-c-mqtt.dll exit 1
about:
  license: Apache-2.0
  license_file: LICENSE
  summary: C99 implementation of the MQTT 3.1.1 specification.
  homepage: https://github.com/awslabs/aws-c-mqtt

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
