schema_version: 1

context:
  version: "0.16.2"

package:
  name: aws-c-mqtt
  version: ${{ version }}

source:
  url: https://github.com/awslabs/aws-c-mqtt/archive/v${{ version }}.tar.gz
  sha256: 0a4da233f2532203b245d2459e4b12c9e556fee5ed2c92185d5e3f1dd4289c8c

build:
  number: 1

requirements:
  build:
    - cmake
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ninja
  host:
    - aws-c-common
    - aws-c-io
    - aws-c-http
  run_exports:
    - ${{ pin_subpackage("aws-c-mqtt", upper_bound="x.x.x") }}

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/lib/libaws-c-mqtt${SHLIB_EXT}
          - test -f $PREFIX/include/aws/mqtt/mqtt.h
      - if: win
        then:
          - if not exist %LIBRARY_INC%\\aws\\mqtt\\mqtt.h exit 1
          - if not exist %PREFIX%\\Library\\bin\\aws-c-mqtt.dll exit 1
  - if: win and arm64
    then:
      requirements:
        run:
          - ${{ compiler('c') }}
          - cmake
      files:
        recipe:
          - CMakeLists.txt
          - consumer.c
      script:
        - cmake -S . -B consumer-build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="%LIBRARY_PREFIX%"
        - cmake --build consumer-build
        - consumer-build\consumer.exe
        - dumpbin /headers "%LIBRARY_BIN%\aws-c-mqtt.dll" | findstr /I /C:"AA64 machine (ARM64)"
        - dumpbin /headers consumer-build\consumer.exe | findstr /I /C:"AA64 machine (ARM64)"
about:
  license: Apache-2.0
  license_file: LICENSE
  summary: C99 implementation of the MQTT 3.1.1 specification.
  homepage: https://github.com/awslabs/aws-c-mqtt
  repository: https://github.com/awslabs/aws-c-mqtt

extra:
  feedstock-name: aws-c-mqtt
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
